export {default as Navbar} from './Navbar'
export {default as Banner} from './Banner'
export {default as Body} from './Body'
export {default as Footer} from './Footer'
export {default as Login} from './Login'
export {default as Registration} from './Registration'
export {default as About} from './About'
export {default as OtpVerification} from './OtpVerification'
// export {default as TestRegistration } from './TestRegistration'